export const COIN_RANKING_API_KEY = process.env.NEXT_PUBLIC_COIN_RANKING_API_KEY;
export const COIN_RANKING_API_URL = process.env.NEXT_PUBLIC_COIN_RANKING_API_URL;
export const COIN_RANKING_API_HOST = process.env.NEXT_PUBLIC_COIN_RANKING_API_HOST;
