import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

import { Toaster } from 'react-hot-toast';

import { Header, ProgressBar } from '@/components';

import Providers from './providers';

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--font-geist-sans',
});
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--font-geist-mono',
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`min-h-screen bg-background font-sans antialiased ${geistSans.variable} ${geistMono.variable}`}>
            <ProgressBar />
            <Providers>
               <Header />
               <main className="flex grow flex-col">
                  <div className="mx-auto w-full max-w-7xl px-10">{children}</div>
               </main>
               <footer className="flex h-16 w-full items-center justify-center">
                  Design and Built with ❤️ by Roisuladib {new Date().getFullYear()}
               </footer>
            </Providers>
            <Toaster />
         </body>
      </html>
   );
}
